# Generated by Django 3.1.7 on 2021-03-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import upload.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_length', models.CharField(choices=[('Length', 'Total Time')], max_length=8)),
                ('text_format', models.CharField(choices=[('CleanVerbatim', 'Clean Verbatim'), ('Verbatim', 'Full Verbatim')], max_length=19)),
                ('number_of_speakers', models.CharField(choices=[('1', '1 Speaker'), ('2', '2 Speakers'), ('3', '3 Speakers'), ('4', '4+ Speakers'), ('10', '10+ Speakers')], max_length=2)),
                ('timestamps', models.CharField(choices=[('None', 'Not Required'), ('SpeakerChange', 'On Speaker Change'), ('2Minutes', 'Every 2 Minutes')], max_length=13)),
                ('turn_around_time', models.CharField(choices=[('24', '24 Hour'), ('48', '48 Hour'), ('Standard', 'Standard (Up To 4 Days)')], max_length=8)),
                ('audio_quality', models.CharField(choices=[('Bad', 'Bad'), ('Fair', 'Fair'), ('Good', 'Good')], max_length=4)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('InProgress', 'In Progress'), ('Done', 'Completed')], default='Processing', max_length=100)),
                ('saved', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='client_files/%Y/%m/%d', validators=[upload.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_name', models.CharField(default='', max_length=500)),
                ('file_length_mins', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('InProgress', 'In Progress'), ('Done', 'Completed')], default='Processing', max_length=100)),
                ('transcript_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='upload.transcriptdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcript_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='upload.transcriptdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
